services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${COMPOSE_MYSQL_DATABASE}'
      - 'MYSQL_PASSWORD=${COMPOSE_MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${COMPOSE_MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_USER=${COMPOSE_MYSQL_USER}'
    ports:
      - '3306:3306'
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:latest'
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_PID=express'
      - 'MSSQL_SA_PASSWORD=${COMPOSE_MSSQL_SA_PASSWORD}'
    ports:
      - '1433'
